#!/bin/bash

if ! command -v flask &> /dev/null
then
    echo "Flask could not be found. Please ensure it is installed and accessible."
    exit 1
fi

echo "deleting migrations folder"
rm -rf migrations

echo "Initializing Flask-Migrate..."
flask db init

echo "Running Migration"
flask db migrate -m "initial migration"

echo "Creating an autogenerated migration..."
flask db revision --autogenerate -m "Autogenerated migration"

echo "Applying the migrations..."
flask db upgrade head

echo "Database migration completed successfully!"
