#!/bin/bash

if ! command -v flask &> /dev/null
then
    echo "Flask could not be found. Please ensure it is installed and accessible."
    exit 1
fi

if [ -d "migrations" ]; then
    echo "Migrations folder exists. Skipping init and migrate steps."
    echo "Creating an autogenerated migration..."
    flask db revision --autogenerate -m "Autogenerated migration"
else
    echo "Deleting migrations folder"
    rm -rf migrations

    echo "Initializing Flask-Migrate..."
    flask db init

    echo "Running Migration"
    flask db migrate -m "initial migration"

    echo "Creating an autogenerated migration..."
    flask db revision --autogenerate -m "Autogenerated migration"
fi

echo "Applying the migrations..."
flask db upgrade head

echo "Database migration completed successfully!"

if [[ "$(uname)" == "Linux" || "$(uname)" == "Darwin" ]]; then
    python3 seed.py
else
    python seed.py
fi
